### ISSUE TITLE
Sugar does not show the right case percentage when combined with "--workers"

### ISSUE THREAD

**Issue by binbinlv** [Teemu/pytest-sugar#229] opened 2022-01-11 04:02 UTC
When reporting an issue, include a way to reproduce the bug. For example:

#### Command used to run pytest
pytest ./ --tags L0 --workers 4 --host ***

#### Test file
Any test cases

#### Output

It is always 0%

```
 ........                                                                               0%
                                                                                         0%
                                                                                         0%
                                                                                         0%
                                                                                         0%
                                                                                         0%
                                                                                          0%
                                                                                         0%
                                                                                         0%
 ........                                                                                0%
```

**Comment by Teemu** [comment] 2022-11-05 08:51
This is a duplicate of https://github.com/Teemu/pytest-sugar/issues/218 right?

**Closed by Teemu** 2022-11-05 08:51 UTC
Labels: 3rd-party
