### ISSUE TITLE
Missing git tag

### ISSUE THREAD

**Issue by kloczek** [Teemu/pytest-sugar#226] opened 2021-09-09 17:57 UTC
According to https://pypi.org/project/pytest-sugar/ latest version is 0.9.4 however there is no here in the repo tag for that version.

**Comment by kloczek** [comment] 2022-04-09 19:39
gentle ping 😃

**Comment by kloczek** [comment] 2022-05-21 16:05
Really please add at least last release tag.
Without that it is now hard to track what has been added/fixed since last release 😞

**Comment by Teemu** [comment] 2022-11-05 08:53
Duplicate of https://github.com/Teemu/pytest-sugar/issues/137

**Closed by Teemu** 2022-11-05 08:53 UTC
Labels: enhancement
